# Generated by Django 3.1.4 on 2020-12-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201202_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='blog',
            field=models.ManyToManyField(related_name='comments', to='blog.Blog'),
        ),
    ]
